name: text_analytics
channels:
  - anaconda
  - defaults
dependencies:
  - tk=8.6.7
  - alabaster=0.7.10
  - asn1crypto=0.24.0
  - astroid=1.6.1
  - babel=2.5.3
  - bleach=2.1.3
  - ca-certificates=2017.08.26
  - certifi=2018.1.18
  - cffi=1.11.5
  - chardet=3.0.4
  - cloudpickle=0.5.2
  - colorama=0.3.9
  - cryptography=2.1.4
  - cymem=1.31.2
  - cytoolz=0.8.2
  - decorator=4.2.1
  - dill=0.2.7.1
  - docutils=0.14
  - entrypoints=0.2.3
  - ftfy=4.4.3
  - git=2.16.1
  - html5lib=1.0.1
  - icc_rt=2017.0.4
  - icu=58.2
  - idna=2.6
  - imagesize=1.0.0
  - intel-openmp=2018.0.0
  - ipykernel=4.8.2
  - ipython=6.2.1
  - ipython_genutils=0.2.0
  - isort=4.3.4
  - jedi=0.11.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter_client=5.2.2
  - jupyter_core=4.4.0
  - lazy-object-proxy=1.3.1
  - libpng=1.6.34
  - markupsafe=1.0
  - mccabe=0.6.1
  - mistune=0.8.3
  - mkl=2018.0.1
  - msgpack-numpy=0.4.1
  - murmurhash=0.28.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - nltk=3.2.5
  - numpy=1.14.1
  - numpydoc=0.7.0
  - openssl=1.0.2n
  - packaging=17.1
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.1.1
  - pathlib=1.0.1
  - pickleshare=0.7.4
  - pip=9.0.1
  - plac=0.9.6
  - preshed=1.0.0
  - prompt_toolkit=1.0.15
  - psutil=5.4.3
  - pycodestyle=2.3.1
  - pycparser=2.18
  - pyflakes=1.6.0
  - pygments=2.2.0
  - pylint=1.8.2
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pyreadline=2.1
  - pysocks=1.6.8
  - python=3.6.4
  - python-dateutil=2.6.1
  - pytz=2018.3
  - pyzmq=17.0.0
  - qt=5.6.2
  - qtawesome=0.4.4
  - qtconsole=4.3.1
  - qtpy=1.3.1
  - regex=2017.4.5
  - requests=2.18.4
  - rope=0.10.7
  - setuptools=38.5.1
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sphinx=1.7.1
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.0.1
  - spyder=3.2.7
  - sqlite=3.22.0
  - termcolor=1.1.0
  - testpath=0.3.1
  - thinc=6.10.1
  - toolz=0.9.0
  - tornado=5.0
  - tqdm=4.19.5
  - traitlets=4.3.2
  - typing=3.6.4
  - ujson=1.35
  - urllib3=1.22
  - vc=14
  - vs2015_runtime=14.0.25123
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.30.0
  - win_inet_pton=1.0.1
  - wincertstore=0.2
  - wrapt=1.10.11
  - zlib=1.2.11
  - pip:
    - attrs==17.4.0
    - backports.csv==1.0.5
    - beautifulsoup4==4.6.0
    - cheroot==6.0.0
    - cherrypy==14.0.0
    - docx==0.2.4
    - en-core-web-sm==2.0.0
    - feedparser==5.2.1
    - future==0.16.0
    - lxml==4.1.1
    - more-itertools==4.1.0
    - msgpack-python==0.5.4
    - mysqlclient==1.3.12
    - pattern==2.6
    - pdfminer.six==20170720
    - pdfminer3k==1.3.1
    - pillow==5.0.0
    - pluggy==0.6.0
    - ply==3.11
    - portend==2.2
    - py==1.5.2
    - pycryptodome==3.4.11
    - pypiwin32==223
    - pytest==3.4.2
    - python-docx==0.8.6
    - pywin32==223
    - scipy==1.0.0
    - simplejson==3.13.2
    - spacy==2.0.9
    - tempora==1.10
prefix: C:\Users\Jan\Anaconda3\envs\text_analytics

